/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wzhy_ndkdemo1_MainActivity */

#ifndef _Included_com_wzhy_ndkdemo1_MainActivity
#define _Included_com_wzhy_ndkdemo1_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wzhy_ndkdemo1_MainActivity
 * Method:    getCStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wzhy_ndkdemo1_MainActivity_getJniStr
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
